spring:
  application:
    name: heysoGateBE
  datasource:
    url: jdbc:mysql://localhost:3306/HeysoGate?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml  # 매퍼 XML 위치
  type-aliases-package: heysoGate.domain       # 도메인 패키지
  configuration:
    map-underscore-to-camel-case: true         # DB 컬럼명 -> 자바 카멜케이스 자동 매핑
