spring:
  application:
    name: heysoGateBE
# p6spy 사용시
  datasource:
    url: jdbc:p6spy:mariadb://localhost:3306/HeysoGate?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/**/*.xml  # 매퍼 XML 위치
  type-aliases-package: heysoGate.domain       # 도메인 패키지
  configuration:
    map-underscore-to-camel-case: true         # DB 컬럼명 -> 자바 카멜케이스 자동 매핑
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

server:
  servlet:
    context-path: /api/v1

jwt:
  secret: DEV
  expiration: DEV